runtime: nodejs10
env: flex
service: dev-cllctive-frontend
handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html



# staging.alpha-247519.appspot.com
